### ISSUE TITLE
Estimation problem: 'division by 0'

### ISSUE THREAD

**Issue by BArFinrod** [samplics-org/samplics#33]
Hi. First of all, thanks!, this is a very usefull package!.
I have a problem and i think it's because the sample size in a group and the method of estimation. It is returning me "division by 0" problem.
![image](https://user-images.githubusercontent.com/68872465/127792218-a64c3ec5-ed31-4eea-96d2-30c7d403781f.png)
I think the part that's interesting is this:
![image](https://user-images.githubusercontent.com/68872465/127792237-7b769552-b8e5-405d-93da-260ed046fed9.png)

I think it has to be something with the sample in each strata:
![image](https://user-images.githubusercontent.com/68872465/127792268-99dd2967-f9af-48aa-b33b-b82edffae05c.png)
When i drop the strata 3, that has just 1 observation, it works fine:
![image](https://user-images.githubusercontent.com/68872465/127792292-7231be42-e138-4f59-a0a7-1e8757a46afc.png)

Thanks!

**Comment by BArFinrod** [comment]
In addition, I run the estimation in STATA, with svyset command and default settings and works fine.

**Comment by MamadouSDiallo** [comment]
Hi

Thank you for reporting this bug. My suspicion is that the number of PSUs in the stratum is one. 
It is possible to share a minimum reproducible example that is code+data? 
You can send an email if that is easier msdialloo@samplics.org.

Best regards

**Comment by BArFinrod** [comment]
Try with this file:
[IPM3 - copia.txt](https://github.com/samplics-org/samplics/files/6914138/IPM3.-.copia.txt)

using this code:

`import samplics
from samplics.estimation import TaylorEstimator, ReplicateEstimator
import pandas as pd

IPM3 = pd.read_csv('file.txt')


def Mean(IPM, var): # IPM debe contener los pesos
    IPM = IPM.reset_index()
    mean = TaylorEstimator("mean")
    mean.estimate(
        y=IPM[var],
        samp_weight=IPM["factor07"],
        stratum=IPM["estrato"],
        psu=IPM["conglome"])
    return pd.Series([mean.point_est, mean.stderror], index=['Mean','SE'])

# no Error
IPM3.groupby('dpto').apply(Mean, "mieperho")

# Error when we only use cases that have values different from 0 in "IPM_censored"
IPM3.loc[IPM3["IPM_censored"]!=0].groupby('dpto').apply(Mean, "mieperho")
`

**Comment by BArFinrod** [comment]
the problem may be in
![image](https://user-images.githubusercontent.com/68872465/127799814-518c8b68-bf57-45a3-99e2-4a9c835ab138.png)
when dividing by n-1

**Comment by MamadouSDiallo** [comment]
Yes, if you have only one PSU then variance cannot be calculated for that stratum that is n-1=0. 
So the approach can be either drop that stratum or use a lower level to compute the variance. 
I will look at solutions from other software and make a decision for samplics.

**Comment by BArFinrod** [comment]
Thanks! this may help:
https://www.stata.com/manuals13/svysvyset.pdf (at the end of page 4)

**Comment by MamadouSDiallo** [comment]
Hi, 

I updated samplics and modified your code to work. Basically, I added the parameter singletons which indicate the option for dealing with the singletons. The options are guided by an ENUM class called SinglePSUEst; see parameter single_psu. The Enum takes these four options: error, skip, certainty, and combine.

```{python}
class SinglePSUEst(Enum):
    """Estimation options for strata with singleton PSU"""

    error = "Raise Error when one PSU in a stratum"
    skip = "Set variance to zero and skip stratum with one PSU"
    certainty = "Use SSUs or lowest units to estimate the variance"
    combine = "Combine the strata with the singleton psu to another stratum"
```

The way to use the four options are the following:

- single_psu=SinglePSUEst.error: Let it crash. This good for the first run to identify your singletons
- single_psu=SinglePSUEst.skip: skip the singletons and set the variance to 0.
- single_psu=SinglePSUEst.certainty: treat the singletons as certainties and use SSU (if provided) or the individual records to estimate the variance
- single_psu=SinglePSUEst.combine: combine the singletons strata to other strata. You will have to specify strata_comb. strata_comb is a dictionary to map the old strata to the new strata i.e. {old_stratum1: new_stratum1, old_stratum2: new_straum2, ...}

Given the above, here is your modified code (I used "skip" but your should be able to use the other options)

```{python}
import pandas as pd
from samplics.estimation import ReplicateEstimator, TaylorEstimator
from samplics.utils import SinglePSUEst

IPM3 = pd.read_csv("IPM3.txt")


def Mean(IPM, var, singletons):  # IPM debe contener los pesos
    IPM = IPM.reset_index()
    mean = TaylorEstimator("mean")
    mean.estimate(
        y=IPM[var],
        samp_weight=IPM["factor07"],
        stratum=IPM["estrato"],
        psu=IPM["conglome"],
        single_psu=singletons,
    )
    return pd.Series([mean.point_est, mean.stderror], index=["Mean", "SE"])



# Run 1
IPM3.groupby("dpto").apply(Mean, "mieperho", SinglePSUEst.skip)

# Run 2: Error when we only use cases that have values different from 0 in "IPM_censored"
IPM3.loc[IPM3["IPM_censored"] != 0].groupby("dpto").apply(Mean, "mieperho", SinglePSUEst.skip)
```

With regards
