### ISSUE TITLE
weird dependency on pandas 1.5.3 when upgrading to samplics 0.4.11

### ISSUE THREAD

**Issue by mondjef** [samplics-org/samplics#53]
I don't know why, but when I try to upgrade samplics package from 0.4.10 to 0.4.11 it wants to downgrade my pandas from 2.2.1 to 1.5.3.  Any ideas?  From what I can tell from the source code this is not indicated in the requirements.txt file or anywhere else so I am not sure why it wants to do that.

**Comment by kevintcaron** [comment]
I had the same issue but was able to resolve this by installing samplics with no dependencies.  

`pip install samplics --no-deps
`

You may need to pip install several other dependencies manually afterward, but it has worked for me so far.

**Comment by MamadouSDiallo** [comment]
Today I will update the dependency (0.4.12). Thanks

**Comment by mondjef** [comment]
> I had the same issue but was able to resolve this by installing samplics with no dependencies.
> 
> `pip install samplics --no-deps `
> 
> You may need to pip install several other dependencies manually afterward, but it has worked for me so far.

Thanks.  I ended up upgrading samplics and letting it downgrade my pandas then afterwards I upgraded my pandas back to 2.2.2. Same end result... different path I guess

**Comment by mondjef** [comment]
> Today I will update the dependency (0.4.12). Thanks

Thank you for such a quick response!
