### ISSUE TITLE
Getting Started Documentation Issue

### ISSUE THREAD

**Issue by kevintcaron** [samplics-org/samplics#54]
Hello, 

It looks like the [Getting Started](https://samplics-org.github.io/samplics/pages/getting_started.html) documentation suggests the use of the following code snippet:

`import samplics
from samplics.estimation import **<span style="color: yellow;">TaylorEstimation<span>**, ReplicateEstimator

zinc_mean_str = TaylorEstimator("mean").estimate(
    y=nhanes2f["zinc"],
    samp_weight=nhanes2f["finalwgt"],
    stratum=nhanes2f["stratid"],
    psu=nhanes2f["psuid"],
    exclude_nan=True
)

ratio_wgt_hgt = ReplicateEstimator("brr", "ratio").estimate(
    y=nhanes2brr["weight"],
    samp_weight=nhanes2brr["finalwgt"],
    x=nhanes2brr["height"],
    rep_weights=nhanes2brr.loc[:, "brr_1":"brr_32"],
    exclude_nan = True
)`

However, the __init__.py file for samplics.estimation uses **<span style="color: yellow;">TaylorEstimator<span>**, not **<span style="color: yellow;">TaylorEstimation<span>**. This caused me some confusion until I reoslved the issue by editing the provided snippet.  Please consider updating the getting started material.

Thanks for your work on this awesome project!

Kevin

**Comment by MamadouSDiallo** [comment]
Will fix the issue, thanks for reporting.

**Comment by kevintcaron** [comment]
I noticed one other thing. I believe in this part of the snippet the current version of samplics uses remove_nan instead of exclude_nan as a param.  

zinc_mean_str = TaylorEstimator("mean").estimate(
    y=nhanes2f["zinc"],
    samp_weight=nhanes2f["finalwgt"],
    stratum=nhanes2f["stratid"],
    psu=nhanes2f["psuid"],
    **exclude_nan**=True
)

exclude_nan does not work for me, but remove_nan does.

**Comment by MamadouSDiallo** [comment]
I believe this was fixed. Thanks.
